
useAxis: 'ev.setUseAxis',

axisXTitle               :'ev.setAxisXTitle',
axisXTitleColor          :'ev.setAxisXTitleColor',
axisXTitleFontSize       :'ev.setAxisXTitleFontSize',
axisXTitleFontFamily     :'ev.setAxisXTitleFontFamily',
axisXTitleDistance       :'ev.setAxisXTitleDistance',
axisXLineColor           :'ev.setAxisXLineColor',
axisXLineWidth           :'ev.setAxisXLineWidth',
axisXTickLineColor       :'ev.setAxisXTickLineColor',
axisXTickLineWidth       :'ev.setAxisXTickLineWidth',
axisXTickLineLength      :'ev.setAxisXTickLineLength',
axisXTickNum             :'ev.setAxisXTickNum',
axisXTickLabelDistance   :'ev.setAxisXTickLabelDistance',
axisXTickLabelDig        :'ev.setAxisXTickLabelDig',
axisXTickLabelColor      :'ev.setAxisXTickLabelColor',
axisXTickLabelFontSize   :'ev.setAxisXTickLabelFontSize',
axisXTickLabelFontFamily :'ev.setAxisXTickLabelFontFamily',
